server:
  address: 0.0.0.0
  port: 8099
#开发环境

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.206.0.5:3306/imooc-red-book-dev?characterEncoding=utf-8
    username: root
    password: song1314
    hikari:
      connection-timeout: 30000 #等待连接池分配连接的最大时间
      minimum-idle: 5  #最小连接数
      maximum-pool-size: 20 #最大连接数
      auto-commit: true #自动提交
      idle-timeout: 600000 #连接超时的最大时长，超时则释放
      pool-name: DataSourceHikariCP #连接池名字
      connection-test-query: SELECT 1
  redis:
    host: 10.206.0.5
    port: 6379
    database: 0
    password: song1314
  data:
    mongodb:
      # 主机地址
      host: 10.206.0.5
      # 数据库
      database: red-book
      # 默认端口是27017
      port: 27017
      username: root
      password: song1314
#  rabbitmq:
#    host: 10.206.0.5
#    port: 5672
#    username: admin
#    password: admin
#    virtual-host: weiyin
  application:
    name: weiyin-nacos
    #作为微服务的名字，进行注册
  cloud:
    nacos:
      discovery:
        server-addr: 10.206.0.5:8848    #nacos所在的地址
management:
  endpoint:
    web:
      exposure:
        include: '*'
minio:
  endpoint: http://129.211.214.9:9000      # MinIO服务地址,api通信地址
  fileHost: http://129.211.214.9:9000      # 文件地址host
  bucketName: imooc                      # 存储桶bucket名称
  accessKey: root                         # 用户名
  secretKey: song1314                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m